language: python

python:
  - 3.6
  - 3.5

install:
  - pip3 install -r requirements.txt
  - pip3 install .

before_script:
  - cd example
  - flake8 example --exclude=migrations,settings.py,wsgi.py
  - flake8 ../singleton_model/ --exclude=__init__.py
  - pylint example
  - pylint ../singleton_model/

script:
  - ./manage.py makemigrations
  - ./manage.py migrate
  - ./manage.py test
